<%@page import="java.sql.Connection"%>
<%@page import="java.sql.DriverManager"%>
<%@page import="java.sql.PreparedStatement"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>Send Query</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .form-container {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 350px;
            text-align: center;
        }
        h2 {
            margin-bottom: 20px;
        }
        form {
            display: flex;
            flex-direction: column;
        }
        label {
            text-align: left;
            margin-top: 10px;
        }
        textarea {
            padding: 8px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
            width: 100%;
        }
        button {
            margin-top: 15px;
            padding: 10px;
            background: #28a745;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background: #218838;
        }
        a {
            display: inline-block;
            margin-top: 10px;
            text-decoration: none;
            color: #007bff;
        }
        a:hover {
            text-decoration: underline;
        }
         .form-container {
            width: 50%;
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px #d4a762;
            text-align: center;
        }
           .back{
  background: black;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
    transition: background 0.3s ease;
  }
    </style>
</head>
<body>

<div class="form-container">
    <h2>Send Query</h2>
    <form action="sendquery.jsp" method="post">
        <label for="query">Your Query:</label>
        <textarea id="query" name="query" rows="4" required></textarea>

        <button type="submit" style=background-color:#d4a762>Send</button>
    </form>
    <a href="customerdashboard.jsp" class='back'>Back</a>
</div>

<%
    // Ensure the form is submitted before processing
    if (request.getMethod().equalsIgnoreCase("POST")) {
        String userQuery = request.getParameter("query");

        // Get email from session (ensure user is logged in)
        String email = (String) session.getAttribute("username");
        if (email == null) {
            response.sendRedirect("login.jsp");
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/event", "root", "root");

            // Insert the query into the database (id is autogenerated)
            PreparedStatement pst = conn.prepareStatement("INSERT INTO query(email, query) VALUES (?, ?)");
            pst.setString(1, email);
            pst.setString(2, userQuery);

            int i = pst.executeUpdate();
            conn.close();

            if (i == 1) {
                out.println("<script>");
                out.println("alert('Query sent successfully!');");
                out.println("window.location.href='viewresponse.jsp';");
                out.println("</script>");
            }
        } catch (Exception e) {
            e.printStackTrace();
            out.println("<script>");
            out.println("alert('Error sending query. Please try again.');");
            out.println("</script>");
        }
    }
%>

</body>
</html>
